//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp5 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp5.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e2dcdb3b85d1a123bfc2afb2842fc959.
        /// </summary>
        internal static string Apikey {
            get {
                return ResourceManager.GetString("Apikey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atmoshphere:.
        /// </summary>
        internal static string Atmoshphere {
            get {
                return ResourceManager.GetString("Atmoshphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bengaluru.
        /// </summary>
        internal static string Bengaluru {
            get {
                return ResourceManager.GetString("Bengaluru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C.
        /// </summary>
        internal static string Celcius {
            get {
                return ResourceManager.GetString("Celcius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °F.
        /// </summary>
        internal static string Farenheit {
            get {
                return ResourceManager.GetString("Farenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 seconds.
        /// </summary>
        internal static string fifteen {
            get {
                return ResourceManager.GetString("fifteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 seconds.
        /// </summary>
        internal static string five {
            get {
                return ResourceManager.GetString("five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity:.
        /// </summary>
        internal static string Humidity {
            get {
                return ResourceManager.GetString("Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        internal static string Kelvin {
            get {
                return ResourceManager.GetString("Kelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madikeri.
        /// </summary>
        internal static string Madikeri {
            get {
                return ResourceManager.GetString("Madikeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature:.
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 seconds.
        /// </summary>
        internal static string ten {
            get {
                return ResourceManager.GetString("ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varanasi.
        /// </summary>
        internal static string Varanasi {
            get {
                return ResourceManager.GetString("Varanasi", resourceCulture);
            }
        }
    }
}
